.PHONY: clean All

All:
	@echo "----------Building project:[ ClassInFile - Debug ]----------"
	@cd "ClassInFile" && "$(MAKE)" -f  "ClassInFile.mk"
clean:
	@echo "----------Cleaning project:[ ClassInFile - Debug ]----------"
	@cd "ClassInFile" && "$(MAKE)" -f  "ClassInFile.mk" clean
