.PHONY: clean All

All:
	@echo "----------Building project:[ Class_In_File - Debug ]----------"
	@cd "Placing_Classes_in_different_file" && "$(MAKE)" -f  "Class_In_File.mk"
clean:
	@echo "----------Cleaning project:[ Class_In_File - Debug ]----------"
	@cd "Placing_Classes_in_different_file" && "$(MAKE)" -f  "Class_In_File.mk" clean
