.PHONY: clean All

All:
	@echo "----------Building project:[ basics - Debug ]----------"
	@cd "basics" && "$(MAKE)" -f  "basics.mk"
clean:
	@echo "----------Cleaning project:[ basics - Debug ]----------"
	@cd "basics" && "$(MAKE)" -f  "basics.mk" clean
